linters:
  presets:
    - bugs
    - error
    - unused
    - comment
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
  disable:
    - wrapcheck
    - err113
    - depguard
    - tagalign
    - godot
    - gci
    - gofumpt
