name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1
        with:
          go-version: '1.21'
      - name: golangci-lint-server
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          working-directory: ./server
      - name: golangci-lint-forwarder
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          working-directory: ./forwarder
      - name: golangci-lint-recorder
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          working-directory: ./recorder