name: nilaway
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  nilaway-server:
    name: nilaway-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1
        with:
          go-version: '1.21'
      - name: download nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest
#      - name: cd to server
#        run: cd server && nilaway .
      - name: run nilaway on server
        run: cd server && nilaway .

  nilaway-forwarder:
    name: nilaway-forwarder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1
        with:
          go-version: '1.21'
      - name: download nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest
#      - name: cd to forwarder
#        run: cd forwarder
      - name: run nilaway on forwarder
        run: cd forwarder && nilaway .

  nilaway-recorder:
    name: nilaway-recorder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1
        with:
          go-version: '1.21'
      - name: download nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest
#      - name: cd to recorder
#        run: cd recorder
      - name: run nilaway on recorder
        run: cd recorder && nilaway .

  nilaway-common:
    name: nilaway-common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1
        with:
          go-version: '1.21'
      - name: download nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest
#      - name: cd to common
#        run: cd common
      - name: run nilaway on common
        run: cd common && nilaway .
