name: nilaway
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  nilaway:
    name: nilaway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1
        with:
          go-version: '1.21'
      - name: download nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest
      - name: run nilaway
        run: nilaway .
